"""Sprint 13: auth, workspaces, roles, api keys upgrade

Revision ID: cb1044fcd9bb
Revises: 6d4b7d70bb22
Create Date: 2026-03-13 18:16:17.499641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1044fcd9bb'
down_revision: Union[str, Sequence[str], None] = '6d4b7d70bb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    with op.batch_alter_table('api_keys') as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rate_limit', sa.Integer(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_api_keys_workspace', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('projects') as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_workspace', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=64), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=False, server_default='engineer'))
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_foreign_key('fk_users_workspace', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_workspace', type_='foreignkey')
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')
        batch_op.drop_column('workspace_id')
        batch_op.drop_column('role')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('avatar')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint('fk_projects_workspace', type_='foreignkey')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('api_keys') as batch_op:
        batch_op.drop_constraint('fk_api_keys_workspace', type_='foreignkey')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('last_ip')
        batch_op.drop_column('usage_count')
        batch_op.drop_column('rate_limit')
        batch_op.drop_column('permissions')
        batch_op.drop_column('description')
        batch_op.drop_column('workspace_id')

    op.drop_table('workspace_members')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
